### ISSUE TITLE
Impossible de charger l'extension 'histo_googlemaps/histo_googlemaps' 

### ISSUE THREAD

**Issue by 4estone** [mastersigat/ExploGooglePosition#1]
`ModuleNotFoundError: No module named 'histo_googlemaps/histo_googlemaps' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'histo_googlemaps/histo_googlemaps'`

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.7-Firenze Firenze, fedae0eb52

**Comment by afourneyron** [comment]
Hi team!  
Thanks for developing this plugin.
Unfortunately same mistake with other versions.

`Traceback (most recent call last):`
  `File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 404, in loadPlugin
    __import__(packageName)`
  `File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)`
`ModuleNotFoundError: No module named 'histo_googlemaps/histo_googlemaps'`

Version de Python : 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
Version de QGIS : 3.36.1-Maidenhead Maidenhead, 3e589453 

----

@4estone after the error message, the plugin appears, with the option of launching the icon and entering the paths to the JSON, SHP and CSV files 👍 

⚠️ Warning ⚠️ 
when entering file paths, it's important to specify the .CSV, .SHP extension, otherwise the plugin won't work.
maybe this could be an improvement for a future version (add the default extension).

----

Thanks again for the developments, it's a really interesting solution, we can imagine lots of future contributions and improvements to the analysis of our data. 

Good luck with your studies ☺️
